version: '3'
services:
  broker:
    image: eclipse-mosquitto:1.6.9
    volumes: 
      - broker-data:/mosquitto/data
      - broker-logs:/mosquitto/log
      - broker-conf:/mosquitto/
    networks: 
      cluster_net:
        ipv4_address: "172.19.1.2"

  clientA:
    image: eclipse-mosquitto:1.6.9
    volumes: 
      - broker-data:/mosquitto/data
      - broker-logs:/mosquitto/log
      - broker-conf:/mosquitto/
    networks: 
        cluster_net: 
            ipv4_address: "172.19.1.3"
          

  clientB:
    image: eclipse-mosquitto:1.6.9
    volumes: 
      - broker-data:/mosquitto/data
      - broker-logs:/mosquitto/log
      - broker-conf:/mosquitto/
    networks: 
      cluster_net: 
        ipv4_address: "172.19.1.4"

  # attacker:
  #   image: kalilinux/kali-rolling:latest
  
  #   tty: true
  #   #command: "apt-get update"
  #   #command:  "apt-get install -y nmap"
  #   networks: 
  #     cluster_net: 
  #       ipv4_address: "172.19.1.15"

    ports: 
      - "4222:22"

networks: 
    cluster_net:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: "172.19.1.0/24"
    
volumes: 
  broker-data:
  broker-logs:
  broker-conf:
